name: three_js_advanced_loaders
description: "Flutter advanced loaders package e.g.(gltf, glb and fbx) converted from threejs and three_dart package."
version: 0.1.1
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_advanced_loaders

topics:
  - gltf
  - collada
  - usda
  - flutter3d
  - model3d

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  archive: ^4.0.5
  xml: ^6.5.0
  flutter:
    sdk: flutter
  three_js_core:
    path: ../three_js_core/
    version: any
  three_js_core_loaders:
    path: ../three_js_core_loaders/
    version: any
  three_js_curves:
    path: ../three_js_curves/
    version: any
  three_js_math:
    path: ../three_js_math/
    version: any
  three_js_geometry:
    path: ../three_js_geometry/
    version: any
  three_js_animations:
    path: ../three_js_animations/
    version: any
  three_js_controls:
    path: ../three_js_controls/
    version: any
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
