name: three_js_bvh_csg
description: "Flutter three_js_bvh_csg is a api that helps with cutting and combining meshes in three_js."
version: 0.1.0
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js_bvh_csg

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_math:
    path: ../three_js_math/
    version: any
  three_js_core:
    path: ../three_js_core/
    version: any
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0